pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v D:/apache-maven-3.6.3/repository'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }

       stage('Test') {
            steps {
                sh 'mvn test'
                }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                    }
            }
       }
    }

}